using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebTerriane.Models
{
    public enum ApplicationStatus
    {
        Pending = 0,
        Approved = 1,
        Rejected = 2
    }

    public class Application
    {
        [Key]
        public int ApplicationId { get; set; }

        // e.g. WT-2026-000001 — generated by IReferenceNumberService using a
        // SQL SEQUENCE, never computed as MAX(Id)+1 in app code (race-prone
        // under concurrent submissions).
        [Required, MaxLength(20)]
        public string ReferenceNumber { get; set; } = string.Empty;

        // Personal details
        [Required, MaxLength(100)]
        public string FullName { get; set; } = string.Empty;

        [Required, MaxLength(100)]
        public string Surname { get; set; } = string.Empty;

        [Required, MaxLength(150), EmailAddress]
        public string Email { get; set; } = string.Empty;

        [Required, MaxLength(20)]
        public string PhoneNumber { get; set; } = string.Empty;

        [Required, MaxLength(20)]
        public string IdNumber { get; set; } = string.Empty;

        // Student details
        [Required, MaxLength(150)]
        public string University { get; set; } = string.Empty;

        [Required, MaxLength(50)]
        public string StudentNumber { get; set; } = string.Empty;

        [Required, MaxLength(150)]
        public string Faculty { get; set; } = string.Empty;

        [Required, MaxLength(20)]
        public string YearOfStudy { get; set; } = string.Empty;

        // Accommodation
        [ForeignKey(nameof(Property))]
        public int PropertyId { get; set; }
        public Property Property { get; set; } = null!;

        public DateTime PreferredMoveInDate { get; set; }

        [MaxLength(2000)]
        public string? AdditionalNotes { get; set; }

        public bool DeclarationAccepted { get; set; }
        public DateTime? DeclarationAcceptedDate { get; set; }

        public ApplicationStatus Status { get; set; } = ApplicationStatus.Pending;

        public DateTime SubmittedDate { get; set; } = DateTime.UtcNow;
        public DateTime? DecisionDate { get; set; }

        [MaxLength(1000)]
        public string? AdminNotes { get; set; } // internal notes when approving/rejecting

        public ICollection<ApplicationDocument> Documents { get; set; } = new List<ApplicationDocument>();
    }
}
